"""empty message

Revision ID: 02fafb99b1db
Revises: cce963297381
Create Date: 2022-03-22 19:55:01.224154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02fafb99b1db'
down_revision = 'cce963297381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('prop_type', sa.String(length=50), nullable=True))
    op.drop_column('properties', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('properties', 'prop_type')
    # ### end Alembic commands ###
