"""empty message

Revision ID: cce963297381
Revises: 6644fec5ca50
Create Date: 2022-03-20 16:18:13.248840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce963297381'
down_revision = '6644fec5ca50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('desc', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'desc')
    # ### end Alembic commands ###
